# Generated by Django 3.2.15 on 2022-08-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Your_Thoughts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='done',
        ),
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='text'),
        ),
    ]
