"""
this code will be converted to SQL by Django and executed on the database when
we run the migrations
"""
# Generated by Django 3.2 on 2022-03-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    this code will be converted to SQL by Django and executed on the
    database when we run the migrations
    """

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
