# Generated by Django 3.2 on 2022-03-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Your_Thoughts', '0003_auto_20220323_1849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
